export default {
    GET_USERS: "GET_USERS",
    GET_USER: "GET_USER",
    GET_MEMBERS: "GET_MEMBERS",
    REG_MEMBER: "REG_MEMBER",
    REG_FAILURE: "REG_FAILURE",
    CHANGE_SEARCHFIELD: "CHANGE_SEARCHFIELD",
    NEWSLETTER_SUB: "NEWSLETTER_SUB",
    NEWSLETTER_SUB_FAILURE: "NEWSLETTER_SUB_FAILURE"
};

